language: php
sudo: required

php:
  - 7.1
  - 7.2

env:
  - DB_USERNAME=root

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install
  - "php -r \"copy('.env.example', '.env');\""

script: phpunit